### PR TITLE
Update nodal_roles.py

### PR DESCRIPTION
**Pull request by mb3152**
fixed within community degree and cleaned up PC

### CODE REVIEW

**Comment by mb3152** [comment]
Please merge this, as the previous nodal roles code is incorrect for within community degree.

**Comment by cgallen** [comment]
What was the problem? It'd be helpful to know how off it was

**Comment by mb3152** [comment]
The order of operations during z-scoring was off because of missing parentheses. We discussed this a while back but my merge broke things because I had version of brainx that was too old. This should be fine, though.

**Comment by mb3152** [comment]
For what it’s worth, I tested this version extensively against the Matlab version of the Brain Connectivity Toolbox, and it always gave the same answers.

**Comment by whitergh** [comment]
I am working on this now. Tests are failing. Did you run them?

-Rob

**Comment by mb3152** [comment]
Ah, I need to rewrite the tests. Give me a few hours. Sorry about that.

**Comment by mb3152** [comment]
Done!

**Comment by whitergh** [comment]
passes tests for me now, but Travis-CI fails, looks like due to problem with ipython notebook (depends on jsonschema, which is not getting installed/loaded). Anybody know anything about this?

-Rob

**Comment by mb3152** [comment]
hmm, is that a problem on my end or in general?

**Comment by rsblume** [comment]
I don't know much, but if you give me the error report I can look. If
travis-ci is failing than most likely it is a general issue. The ipython
notebook that is filing is probably out of date with the version of ipython
travis is testing with.
See this:
https://github.com/ipython/ipython/issues/5979
Someone correct me if I am wrong
Surprising why the test did not fail earlier though...
-Rob

On Wed, Jun 3, 2015 at 11:27 AM, Maxwell Bertolero <notifications@github.com
> wrote:

> hmm, is that a problem on my end or in general?
>
> > On Jun 3, 2015, at 11:26 AM, whitergh <notifications@github.com> wrote:
> >
> > passes tests for me now, but Travis-CI fails, looks like due to problem
> with ipython notebook (depends on jsonschema, which is not getting
> installed/loaded). Anybody know anything about this?
> >
> > -Rob
> >
> > On Jun 3, 2015, at 10:52 AM, Maxwell Bertolero <notifications@github.com>
> wrote:
> > > Done!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/nipy/brainx/pull/34#issuecomment-108561357>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/brainx/pull/34#issuecomment-108561853>.
>



-- 
Robert Blumenfeld, Ph.D.
Assistant Adjunct Professor
Brain Circuits Laboratory
University of California, Irvine

**Pull request merged**
